### ISSUE TITLE
Add the ability to override svg attributes 

### ISSUE THREAD

**Issue by erksdee** [okize/react-calendar-heatmap#111]
Hi, 

I would like the SVG elements to be circles instead of rectangles. To achieve this, I would need to add `rx="100" ry="100"` to each svg element. Just wondering if it's possible to add or override those SVG attributes?

**Comment by kevinsqi** [comment]
Looks like it is possible with the `transformDayElement` prop: https://codesandbox.io/s/react-calendar-heatmap-issue-111-8l9mp

![Screen Shot 2019-07-17 at 10 24 43 PM](https://user-images.githubusercontent.com/396006/61431245-b20fd200-a8e1-11e9-901e-0b1f379c5691.png)

Does that get you what you need?

**Comment by erksdee** [comment]
> Looks like it is possible with the `transformDayElement` prop: https://codesandbox.io/s/react-calendar-heatmap-issue-111-8l9mp
> 
> ![Screen Shot 2019-07-17 at 10 24 43 PM](https://user-images.githubusercontent.com/396006/61431245-b20fd200-a8e1-11e9-901e-0b1f379c5691.png)
> 
> Does that get you what you need?

@kevinsqi thanks for that! exactly what I was looking for.

**Comment by kevinsqi** [comment]
@erksdee awesome!

**Comment by sshah98** [comment]
This was super helpful thank you :)

**Comment by wayneschuller** [comment]
>    transformDayElement={(element, value, index) =>
>           React.cloneElement(element, { rx: 100, ry: 100 })
>         }
> 

This would be worth putting in the docs...
